"""Generate ``src/levels/<name>.py`` from an ``EditorMapSpec`` (optional export)."""

from __future__ import annotations

from .from_json import EditorMapSpec, _AMMO_CONST, _WEAPON_CONST


def _fmt_num(v: float | int) -> str:
    if isinstance(v, float) and v.is_integer():
        v = int(v)
    if isinstance(v, int):
        return f"{v}.0" if abs(v) >= 1000 or v == 0 else str(v)
    return f"{v:.1f}".rstrip("0").rstrip(".")


def _weapon_expr(wid: int) -> str:
    return _WEAPON_CONST.get(wid, f"0x{wid:02x}")


def _ammo_expr(aid: int) -> str:
    return _AMMO_CONST.get(aid, f"0x{aid:02x}")


def render_level_module(spec: EditorMapSpec) -> str:
    """Render a hand-editable level module matching ``spec``."""
    name = spec.name
    g = spec.mapdef
    half = spec.box_half
    height = spec.box_height
    spawn_y = spec.spawn_y

    spawn_pads = [i for i, p in enumerate(g.pads) if any(
        getattr(cmd, "pad", None) == i and cmd.__class__.__name__ == "Spawn"
        for cmd in g.intro
    )]
    weapon_pads: list[tuple[int, int]] = []
    for prop in g.props:
        cls = type(prop).__name__
        if cls == "Weapon":
            weapon_pads.append((prop.pad, prop.weapon))
    ammo_pads: list[tuple[int, int]] = []
    for prop in g.props:
        if type(prop).__name__ == "AmmoCrate":
            ammo_pads.append((prop.pad, prop.ammotype))

    scenario_pads: list[tuple[int, str, int]] = []
    for cmd in g.intro:
        if cmd.__class__.__name__ == "Case":
            scenario_pads.append((cmd.pad, "case", cmd.team))
        elif cmd.__class__.__name__ == "CaseRespawn":
            scenario_pads.append((cmd.pad, "case_respawn", cmd.team))
        elif cmd.__class__.__name__ == "Hill":
            scenario_pads.append((cmd.pad, "hill", 0))

    lines: list[str] = []
    append = lines.append

    append("# Generated by tools/pdmap (from-json export).")
    append("")
    append("from tools.pdmap.builders import (")
    append("    add_loadout_intro,")
    if weapon_pads:
        append("    add_floor_weapons,")
    if ammo_pads:
        append("    add_ammo_row,")
    has_hill = any(sc == "hill" for _, sc, _ in scenario_pads)
    has_ctf = any(sc in ("case", "case_respawn") for _, sc, _ in scenario_pads)
    if has_hill and has_ctf:
        append("    ctf_zones_from_mapdef,")
        append("    floor_box_with_hill_and_ctf_zones,")
    elif has_hill:
        append("    floor_box_with_hill_zone,")
    elif has_ctf:
        append("    ctf_zones_from_mapdef,")
        append("    floor_box_with_ctf_zones,")
    else:
        append("    floor_box_tiles,")
    append(")")
    append("from tools.pdmap.core import MapDef")
    intro_imports: set[str] = set()
    if spawn_pads:
        intro_imports.add("Spawn")
    for _, sc, _ in scenario_pads:
        if sc == "case":
            intro_imports.add("Case")
        elif sc == "case_respawn":
            intro_imports.add("CaseRespawn")
        else:
            intro_imports.add("Hill")
    if intro_imports:
        append(f"from tools.pdmap.intro import {', '.join(sorted(intro_imports))}")
    append("from tools.pdmap import weapons as W")
    append("")
    append(f"BOX_HALF = {_fmt_num(half)}")
    append(f"BOX_HEIGHT = {_fmt_num(height)}")
    append(f"SPAWN_Y = {_fmt_num(spawn_y)}")
    append("")
    append("")
    append("def build() -> MapDef:")
    append(f'    g = MapDef("{name}")')
    append("")
    append("    # --- Pads (indices MUST match array order 0..N-1) ---")
    for i, p in enumerate(g.pads):
        kind = "spawn" if i in spawn_pads else "other"
        for wp, wid in weapon_pads:
            if wp == i:
                kind = "weapon"
        for ap, _ in ammo_pads:
            if ap == i:
                kind = "ammo"
        for sp, sc, _ in scenario_pads:
            if sp == i:
                kind = f"scenario/{sc}"
        append(
            f"    g.add_pad(index={i}, x={_fmt_num(p.x)}, y={_fmt_num(p.y)}, "
            f"z={_fmt_num(p.z)}, room={p.room})  # {kind}"
        )

    if spawn_pads:
        append("")
        append("    # --- Spawn intro commands ---")
        for i in spawn_pads:
            append(f"    g.add_intro(Spawn(pad={i}))")

    if weapon_pads:
        append("")
        append("    # --- Weapon pickups (floor props) ---")
        pairs = ", ".join(f"({i}, {_weapon_expr(wid)})" for i, wid in weapon_pads)
        append(f"    add_floor_weapons(g, [{pairs}])")

    if ammo_pads:
        append("")
        append("    # --- Ammo crates (floor props) ---")
        by_type: dict[int, list[int]] = {}
        for i, aid in ammo_pads:
            by_type.setdefault(aid, []).append(i)
        for aid, indices in sorted(by_type.items()):
            idx_str = ", ".join(str(i) for i in indices)
            append(f"    add_ammo_row(g, [{idx_str}], ammotype={_ammo_expr(aid)})")

    if scenario_pads:
        append("")
        append("    # --- Scenario anchors ---")
        for pad, sc, team in scenario_pads:
            if sc == "case":
                append(f"    g.add_intro(Case(team={team}, pad={pad}))")
            elif sc == "case_respawn":
                append(f"    g.add_intro(CaseRespawn(team={team}, pad={pad}))")
            else:
                append(f"    g.add_intro(Hill(pad={pad}))")

    append("")
    append("    add_loadout_intro(g)")
    append("    return g")
    append("")
    append("")
    append("def build_tiles_json():")
    hill_pad = next((pad for pad, sc, _ in scenario_pads if sc == "hill"), None)
    has_ctf = any(sc in ("case", "case_respawn") for _, sc, _ in scenario_pads)
    if hill_pad is not None and has_ctf:
        hp = g.pads[hill_pad]
        append("    g = build()")
        append("    return floor_box_with_hill_and_ctf_zones(")
        append(f'        "{name}", half=BOX_HALF, y=0.0,')
        append(f"        hill_center_x={_fmt_num(hp.x)}, hill_center_z={_fmt_num(hp.z)},")
        append("        zones=ctf_zones_from_mapdef(g),")
        append("    )")
    elif hill_pad is not None:
        hp = g.pads[hill_pad]
        append(f'    return floor_box_with_hill_zone(')
        append(f'        "{name}", half=BOX_HALF, y=0.0,')
        append(f"        hill_center_x={_fmt_num(hp.x)}, hill_center_z={_fmt_num(hp.z)},")
        append("    )")
    elif has_ctf:
        append("    g = build()")
        append("    return floor_box_with_ctf_zones(")
        append(f'        "{name}", half=BOX_HALF, y=0.0,')
        append("        zones=ctf_zones_from_mapdef(g),")
        append("    )")
    else:
        append(f'    return floor_box_tiles("{name}", half=BOX_HALF, y=0.0, room_index=1)')
    append("")

    return "\n".join(lines)
