# Generated by tools/pdmap (from-json export).

from tools.pdmap.builders import (
    add_loadout_intro,
    floor_box_tiles,
)
from tools.pdmap.core import MapDef
from tools.pdmap.intro import Spawn
from tools.pdmap import weapons as W

BOX_HALF = 2500.0
BOX_HEIGHT = 2000.0
SPAWN_Y = 10


def build() -> MapDef:
    g = MapDef("learn_14_procedural_seg")

    # --- Pads (indices MUST match array order 0..N-1) ---
    g.add_pad(index=0, x=0.0, y=10, z=0.0, room=1)  # spawn

    # --- Spawn intro commands ---
    g.add_intro(Spawn(pad=0))

    add_loadout_intro(g)
    return g


def build_tiles_json():
    return floor_box_tiles("learn_14_procedural_seg", half=BOX_HALF, y=0.0, room_index=1)
