# Generated by tools/pdmap (from-json export).

from tools.pdmap.builders import (
    add_loadout_intro,
    cover_markers_from_mapdef,
    floor_box_with_cover_markers,
)
from tools.pdmap.core import MapDef
from tools.pdmap.intro import Spawn
from tools.pdmap import weapons as W

BOX_HALF = 5000.0
BOX_HEIGHT = 3000.0
SPAWN_Y = 10


SEG_MODE = "marker"


def build() -> MapDef:
    g = MapDef("learn_31_cover_points")

    # --- Pads (indices MUST match array order 0..N-1) ---
    g.add_pad(index=0, x=-2000.0, y=10, z=0.0, room=1)  # spawn
    g.add_pad(index=1, x=2000.0, y=10, z=0.0, room=1)  # spawn

    # --- Spawn intro commands ---
    g.add_intro(Spawn(pad=0))
    g.add_intro(Spawn(pad=1))

    g.add_cover(x=-800.0, z=0.0, y=SPAWN_Y)
    g.add_cover(x=800.0, z=0.0, y=SPAWN_Y)
    add_loadout_intro(g)
    return g


def build_tiles_json():
    g = build()
    return floor_box_with_cover_markers(
        "learn_31_cover_points", half=BOX_HALF, y=0.0,
        markers=cover_markers_from_mapdef(g),
    )
