# Generated by tools/pdmap (from-json export).

from tools.pdmap.builders import (
    HILL_ROOM_INDEX,
    add_loadout_intro,
    floor_box_with_hill_zone,
)
from tools.pdmap.core import MapDef
from tools.pdmap.intro import Hill, Spawn

DEPLOY_AS = "uff"
SEG_MODE = "hill"

BOX_HALF = 2500.0
BOX_HEIGHT = 2000.0
SPAWN_Y = 10

# Hill anchor at +Z — room 2 floor tiles mark the capture zone.
HILL_X = 0.0
HILL_Z = 1500.0


def build() -> MapDef:
    g = MapDef("learn_07_hill")

    # --- Pads (indices MUST match array order 0..N-1) ---
    g.add_pad(index=0, x=0.0, y=10, z=0.0, room=1)  # spawn
    g.add_pad(index=1, x=HILL_X, y=10, z=HILL_Z, room=HILL_ROOM_INDEX)  # scenario/hill

    # --- Spawn intro commands ---
    g.add_intro(Spawn(pad=0))

    # --- Scenario anchors ---
    g.add_intro(Hill(pad=1))

    add_loadout_intro(g)
    return g


def build_tiles_json():
    return floor_box_with_hill_zone(
        "learn_07_hill",
        half=BOX_HALF,
        y=0.0,
        hill_center_x=HILL_X,
        hill_center_z=HILL_Z,
    )
