# Generated by tools/pdmap (from-json export).

from tools.pdmap.builders import (
    add_loadout_intro,
    add_ammo_row,
    floor_box_tiles,
)
from tools.pdmap.core import MapDef
from tools.pdmap.intro import Spawn
from tools.pdmap import weapons as W

BOX_HALF = 2500.0
BOX_HEIGHT = 2000.0
SPAWN_Y = 10


def build() -> MapDef:
    g = MapDef("learn_04_ammo")

    # --- Pads (indices MUST match array order 0..N-1) ---
    g.add_pad(index=0, x=0.0, y=10, z=0.0, room=1)  # spawn
    g.add_pad(index=1, x=1500.0, y=10, z=0.0, room=1)  # ammo

    # --- Spawn intro commands ---
    g.add_intro(Spawn(pad=0))

    # --- Ammo crates (floor props) ---
    add_ammo_row(g, [1], ammotype=W.AMMOTYPE_RIFLE)

    add_loadout_intro(g)
    return g


def build_tiles_json():
    return floor_box_tiles("learn_04_ammo", half=BOX_HALF, y=0.0, room_index=1)
