# Generated by tools/pdmap (from-json export).

from tools.pdmap.builders import (
    add_loadout_intro,
    floor_box_with_hill_zone,
)
from tools.pdmap.core import MapDef
from tools.pdmap.intro import Hill, Spawn
from tools.pdmap import weapons as W

BOX_HALF = 2500.0
BOX_HEIGHT = 2000.0
SPAWN_Y = 10


def build() -> MapDef:
    g = MapDef("learn_07_hill")

    # --- Pads (indices MUST match array order 0..N-1) ---
    g.add_pad(index=0, x=0.0, y=10, z=0.0, room=1)  # spawn
    g.add_pad(index=1, x=0.0, y=10, z=1500.0, room=2)  # scenario/hill

    # --- Spawn intro commands ---
    g.add_intro(Spawn(pad=0))

    # --- Scenario anchors ---
    g.add_intro(Hill(pad=1))

    add_loadout_intro(g)
    return g


def build_tiles_json():
    return floor_box_with_hill_zone(
        "learn_07_hill", half=BOX_HALF, y=0.0,
        hill_center_x=0.0, hill_center_z=1500.0,
    )
