# Generated by tools/pdmap (from-json export).

from tools.pdmap.builders import (
    add_loadout_intro,
    add_floor_weapons,
    ctf_zones_from_mapdef,
    floor_box_with_hill_and_ctf_zones,
)
from tools.pdmap.core import MapDef
from tools.pdmap.intro import Case, CaseRespawn, Hill, Spawn
from tools.pdmap import weapons as W

BOX_HALF = 5000.0
BOX_HEIGHT = 3000.0
SPAWN_Y = 10


def build() -> MapDef:
    g = MapDef("learn_12_testarena_fixture")

    # --- Pads (indices MUST match array order 0..N-1) ---
    g.add_pad(index=0, x=-4000.0, y=10, z=-4000.0, room=1)  # spawn
    g.add_pad(index=1, x=4000.0, y=10, z=-4000.0, room=1)  # spawn
    g.add_pad(index=2, x=-4000.0, y=10, z=4000.0, room=1)  # spawn
    g.add_pad(index=3, x=4000.0, y=10, z=4000.0, room=1)  # spawn
    g.add_pad(index=4, x=0.0, y=10, z=0.0, room=1)  # weapon
    g.add_pad(index=5, x=1500.0, y=10, z=0.0, room=1)  # other
    g.add_pad(index=6, x=0.0, y=10, z=1500.0, room=2)  # scenario/hill
    g.add_pad(index=7, x=-4200.0, y=10, z=-4200.0, room=1)  # scenario/case
    g.add_pad(index=8, x=-4200.0, y=10, z=-4000.0, room=1)  # scenario/case_respawn
    g.add_pad(index=9, x=4200.0, y=10, z=-4200.0, room=1)  # scenario/case
    g.add_pad(index=10, x=4200.0, y=10, z=-4000.0, room=1)  # scenario/case_respawn
    g.add_pad(index=11, x=-4200.0, y=10, z=4200.0, room=1)  # scenario/case
    g.add_pad(index=12, x=-4200.0, y=10, z=4000.0, room=1)  # scenario/case_respawn
    g.add_pad(index=13, x=4200.0, y=10, z=4200.0, room=1)  # scenario/case
    g.add_pad(index=14, x=4200.0, y=10, z=4000.0, room=1)  # scenario/case_respawn

    # --- Spawn intro commands ---
    g.add_intro(Spawn(pad=0))
    g.add_intro(Spawn(pad=1))
    g.add_intro(Spawn(pad=2))
    g.add_intro(Spawn(pad=3))

    # --- Weapon pickups (floor props) ---
    add_floor_weapons(g, [(4, W.WEAPON_CMP150)])

    # --- Scenario anchors ---
    g.add_intro(Hill(pad=6))
    g.add_intro(Case(team=0, pad=7))
    g.add_intro(CaseRespawn(team=0, pad=8))
    g.add_intro(Case(team=1, pad=9))
    g.add_intro(CaseRespawn(team=1, pad=10))
    g.add_intro(Case(team=2, pad=11))
    g.add_intro(CaseRespawn(team=2, pad=12))
    g.add_intro(Case(team=3, pad=13))
    g.add_intro(CaseRespawn(team=3, pad=14))

    add_loadout_intro(g)
    return g


def build_tiles_json():
    g = build()
    return floor_box_with_hill_and_ctf_zones(
        "learn_12_testarena_fixture", half=BOX_HALF, y=0.0,
        hill_center_x=0.0, hill_center_z=1500.0,
        zones=ctf_zones_from_mapdef(g),
    )
